import type { PoolClient } from 'pg';
import { logger } from '../../utils/logger';
import { hashPassword } from '../../utils/password';
import { GUARDIAN_PASSWORD } from './011_school_life.seed';
import { seedTimetable } from './010_timetable.seed';
import { insertMany, makeRandom, pad } from './bulk-insert';
import {
  addDays,
  calendarAround,
  dateWithin,
  elapsedFraction,
  iso,
  schoolDays,
} from './school-calendar';
import type { IsoDate, Semester } from './school-calendar';

/**
 * Builds the academic year the school is living in right now: Semester 1
 * finished and marked, Semester 2 about half taught.
 *
 * The point of this seed is that the two halves must look genuinely different.
 * A finished semester has every mark in, a rank on every report card and no
 * loose ends. A semester still running has a register that stops at today, work
 * that has been set but not yet handed in, subjects whose teacher is behind on
 * marking, and a final examination that exists only as a date. Filling both to
 * the brim would make the system impossible to demonstrate, because every
 * screen that distinguishes "not yet" from "nothing" would look the same.
 *
 * Nothing here is invented independently of anything else. A mark belongs to an
 * assessment, which belongs to a class-subject taught by a named teacher in a
 * term of this year; a submission belongs to an assignment set for that same
 * class and subject; attendance belongs to the enrolment that puts the pupil in
 * that class. Rows are generated by walking those relationships, never by
 * picking identifiers at random.
 */

export const YEAR_NAME = '2025 - 2026';

/**
 * Written to `students.notes` on every pupil this seed invents.
 *
 * The seed has to be able to tell its own generated intake from the real
 * children on the roster, because a re-run must remove the pupils it created
 * last time and must never touch anyone else. Recognising them by their code or
 * their enrolment date would eventually catch a real pupil; an explicit marker
 * cannot.
 */
export const GENERATED_MARKER = 'Generated by the current-year seed';

/** How the ten-subject curriculum is spread over the week, following MoEYS. */
const PERIODS_PER_WEEK: Record<string, number> = {
  KHM: 6, MATH: 6, ENG: 3, PHY: 2, CHEM: 2, BIO: 2,
  EARTH: 1, HIST: 2, GEO: 2, CIVIC: 2,
};

/**
 * The pieces of work each subject is assessed on, and where in the term they
 * fall.
 *
 * The weights match `grading_scheme_components` — homework 10, quizzes 20,
 * midterm 30, final 40 — so a grade calculated here is the same number the
 * application would calculate from the same marks.
 *
 * The positions matter more than they look. With today just under halfway
 * through Semester 2, everything up to the midterm has been sat and everything
 * after it has not, which is what produces a half-marked term rather than a
 * uniformly thin one.
 */
const PIECES: { type: string; label: string; max: number; at: number }[] = [
  { type: 'HOMEWORK', label: 'Homework portfolio', max: 20, at: 0.15 },
  { type: 'QUIZ', label: 'First quiz', max: 20, at: 0.32 },
  { type: 'MIDTERM', label: 'Midterm examination', max: 50, at: 0.44 },
  { type: 'QUIZ', label: 'Second quiz', max: 20, at: 0.70 },
  { type: 'FINAL', label: 'Final examination', max: 100, at: 0.95 },
];

const WEIGHTS: Record<string, number> = { HOMEWORK: 10, QUIZ: 20, MIDTERM: 30, FINAL: 40 };

/** Khmer given names, with the transliteration the school writes on registers. */
const GIVEN_MALE: [string, string][] = [
  ['ចន្ទ្រា', 'Chantrea'], ['រតនៈ', 'Ratanak'], ['ពិសិដ្ឋ', 'Piseth'], ['សុវណ្ណ', 'Sovann'],
  ['ដារ៉ា', 'Dara'], ['វុទ្ធី', 'Vuthy'], ['សំអាង', 'Samang'], ['ប៊ុនធឿន', 'Bunthoeun'],
  ['កុសល', 'Kosal'], ['នរិន្ទ', 'Norin'], ['ភិរុណ', 'Phirun'], ['សុផល', 'Sophal'],
  ['ចន្ថូ', 'Chanthou'], ['សិរីវុទ្ធ', 'Sereivuth'], ['គីមឡុង', 'Kimlong'], ['រ៉ុងឡុង', 'Ronglong'],
  ['សុខា', 'Sokha'], ['វិសាល', 'Visal'], ['ធារ៉ា', 'Theara'], ['បញ្ញា', 'Panha'],
];

const GIVEN_FEMALE: [string, string][] = [
  ['សុគន្ធា', 'Sokuntha'], ['បុប្ផា', 'Bopha'], ['ចន្នារី', 'Channary'], ['ធារី', 'Theary'],
  ['ម៉ាលី', 'Maly'], ['សុជាតា', 'Sochata'], ['នារី', 'Nary'], ['រស្មី', 'Raksmey'],
  ['ស្រីពៅ', 'Sreypov'], ['ធីតា', 'Thida'], ['សុភាព', 'Sopheap'], ['កញ្ញា', 'Kanha'],
  ['មុលិកា', 'Molika'], ['ពិសី', 'Pisey'], ['វណ្ណា', 'Vanna'], ['សុភី', 'Sophy'],
  ['ចន្ថា', 'Chantha'], ['ស្រីនាង', 'Sreyneang'], ['អរុណី', 'Aruny'], ['លីដា', 'Lida'],
];

const FAMILY: [string, string][] = [
  ['សុខ', 'Sok'], ['ចាន់', 'Chan'], ['គឹម', 'Kim'], ['ហេង', 'Heng'], ['លី', 'Ly'],
  ['ពៅ', 'Pov'], ['នូ', 'Nou'], ['សៀង', 'Sieng'], ['យ៉ន', 'Yan'], ['ម៉ៅ', 'Mao'],
  ['ធី', 'Thy'], ['សំ', 'Sam'], ['អ៊ុំ', 'Um'], ['ឆាយ', 'Chhay'], ['រ៉ុន', 'Ron'],
  ['ទន់', 'Ton'], ['ជា', 'Chea'], ['ប៉ុល', 'Pol'], ['វ៉ន', 'Von'], ['ខៀវ', 'Khiev'],
];

const PROVINCES = ['Kampong Cham', 'Tboung Khmum', 'Kratie', 'Prey Veng'];

const OCCUPATIONS = [
  'Farmer', 'Trader', 'Teacher', 'Driver', 'Tailor', 'Shop owner', 'Nurse',
  'Carpenter', 'Mechanic', 'Fisher', 'Civil servant', 'Market seller',
];

interface ClassRow {
  id: number;
  code: string;
  gradeLevelId: number;
  gradeCode: string;
}

interface Pupil {
  studentId: number;
  enrollmentId: number;
  classId: number;
}

/**
 * How a pupil behaves over a year: how well they do, how often they attend and
 * how reliably they hand work in.
 *
 * Drawn once per pupil from their own id, so the same child is the same child
 * in every term and every subject. Rolling these per row instead would give a
 * pupil who is top of the class in one subject and bottom in the next for no
 * reason, and an attendance rate that averages out to the same figure for
 * everybody — which is precisely what makes generated data look generated.
 */
interface Profile {
  ability: number;
  attendance: number;
  diligence: number;
}

const profileFor = (studentId: number): Profile => {
  const draw = makeRandom(studentId * 2654435761);

  // A believable spread rather than a bell curve centred on a pass: a few
  // outstanding pupils, a solid middle, and a tail who are genuinely behind.
  const abilityRoll = draw();
  const ability =
    abilityRoll < 0.12 ? 85 + draw() * 11
    : abilityRoll < 0.45 ? 70 + draw() * 15
    : abilityRoll < 0.83 ? 55 + draw() * 15
    : 38 + draw() * 17;

  const attendanceRoll = draw();
  const attendance =
    attendanceRoll < 0.25 ? 0.970 + draw() * 0.025
    : attendanceRoll < 0.70 ? 0.905 + draw() * 0.065
    : attendanceRoll < 0.90 ? 0.830 + draw() * 0.075
    : 0.720 + draw() * 0.110;

  // Diligence follows ability loosely — hard workers tend to score better — but
  // not exactly, so the roster still holds a bright pupil who never hands in and
  // a weaker one who always does.
  const diligence = Math.max(0.35, Math.min(0.99, (ability / 100) * 0.75 + draw() * 0.4));

  return { ability, attendance, diligence };
};

export interface CurrentYearSummary {
  yearName: string;
  start: IsoDate;
  end: IsoDate;
  today: IsoDate;
  semester2Progress: number;
  counts: Record<string, number>;
}

export const seedCurrentYear = async (client: PoolClient): Promise<CurrentYearSummary> => {
  const random = makeRandom(20260902);
  const counts: Record<string, number> = {};

  const today: IsoDate = (
    await client.query<{ today: string }>('SELECT CURRENT_DATE::text AS today')
  ).rows[0].today;

  const calendar = calendarAround(today);
  const terms: Semester[] = [calendar.semester1, calendar.semester2];

  // --- The year and its two semesters ---------------------------------------
  /**
   * Clear away any year that was set up but never taught.
   *
   * A rollover that was started and abandoned leaves a shell behind: a year with
   * a class or two and the enrolments of the pupils who had been moved into it,
   * but no register, no marks and no report cards. It still occupies its dates,
   * so it blocks the year being built here, and its enrolments would give those
   * pupils a second place in a year they never attended.
   *
   * Only a year with nothing recorded against it is touched. A year that has
   * been taught, even for a day, is left alone and will collide below — which is
   * the right outcome, because deleting one would destroy real records.
   */
  const untaught = (
    await client.query<{ id: number; name: string }>(
      `SELECT y.id, y.name
         FROM academic_years y
        WHERE y.is_active = FALSE
          AND y.start_date <= $2::date AND y.end_date >= $1::date
          AND NOT EXISTS (SELECT 1 FROM attendance WHERE academic_year_id = y.id)
          AND NOT EXISTS (SELECT 1 FROM grades WHERE academic_year_id = y.id)
          AND NOT EXISTS (SELECT 1 FROM report_cards WHERE academic_year_id = y.id)
          AND NOT EXISTS (SELECT 1 FROM assessments WHERE academic_year_id = y.id)`,
      [calendar.start, calendar.end],
    )
  ).rows;

  for (const shell of untaught) {
    if (shell.name === YEAR_NAME) {
      continue;
    }

    const removed = await client.query(
      `DELETE FROM enrollments WHERE academic_year_id = $1`,
      [shell.id],
    );

    await client.query(
      `DELETE FROM class_subjects WHERE class_id IN (SELECT id FROM classes WHERE academic_year_id = $1)`,
      [shell.id],
    );
    await client.query(
      `DELETE FROM teacher_classes WHERE class_id IN (SELECT id FROM classes WHERE academic_year_id = $1)`,
      [shell.id],
    );
    await client.query('DELETE FROM academic_terms WHERE academic_year_id = $1', [shell.id]);
    await client.query('DELETE FROM classes WHERE academic_year_id = $1', [shell.id]);
    await client.query('DELETE FROM academic_years WHERE id = $1', [shell.id]);

    logger.warn(
      `Removed ${shell.name}: it was set up but never taught, ` +
        `and it held ${removed.rowCount ?? 0} enrolment(s) placed by an unfinished rollover`,
    );
  }

  /**
   * The system refuses to let two years overlap, so the year being built must
   * start after the archive ends. Checking it here turns a confusing constraint
   * violation deep in the seed into a sentence that says what went wrong.
   */
  const clash = (
    await client.query<{ name: string; start_date: string; end_date: string }>(
      `SELECT name, start_date::text, end_date::text FROM academic_years
        WHERE name <> $1 AND start_date <= $3::date AND end_date >= $2::date`,
      [YEAR_NAME, calendar.start, calendar.end],
    )
  ).rows[0];

  if (clash) {
    throw new Error(
      `${calendar.start} to ${calendar.end} overlaps academic year ${clash.name} ` +
        `(${clash.start_date} to ${clash.end_date}). Archive that year first.`,
    );
  }

  await client.query('UPDATE academic_years SET is_active = FALSE WHERE is_active');

  const year = (
    await client.query<{ id: number }>(
      `INSERT INTO academic_years (name, start_date, end_date, status, is_active)
       VALUES ($1, $2, $3, 'ACTIVE', TRUE)
       ON CONFLICT (name) DO UPDATE
         SET start_date = EXCLUDED.start_date,
             end_date = EXCLUDED.end_date,
             status = 'ACTIVE',
             is_active = TRUE,
             closed_at = NULL
       RETURNING id`,
      [YEAR_NAME, calendar.start, calendar.end],
    )
  ).rows[0];

  const yearId = year.id;

  /**
   * `academic_terms` records no status of its own, only dates and a flag, so a
   * semester is "finished" because its end date has passed and "in progress"
   * because it holds today. The flag marks the one the school is working in,
   * which is what the term pickers default to.
   */
  const termIds = new Map<number, number>();

  for (const term of terms) {
    const row = (
      await client.query<{ id: number }>(
        `INSERT INTO academic_terms (academic_year_id, name, term_order, start_date, end_date, is_active)
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT (academic_year_id, term_order) DO UPDATE
           SET name = EXCLUDED.name,
               start_date = EXCLUDED.start_date,
               end_date = EXCLUDED.end_date,
               is_active = EXCLUDED.is_active
         RETURNING id`,
        [yearId, term.name, term.order, term.start, term.end, term.end >= today],
      )
    ).rows[0];

    termIds.set(term.order, row.id);
  }

  const taughtPercent = Math.round(
    elapsedFraction(calendar.semester2.start, calendar.semester2.end, today) * 100,
  );

  logger.info(
    `${YEAR_NAME}: ${calendar.start} to ${calendar.end}. ` +
      `${calendar.semester1.name} ${calendar.semester1.start}..${calendar.semester1.end} finished; ` +
      `${calendar.semester2.name} ${calendar.semester2.start}..${calendar.semester2.end} ` +
      `${taughtPercent}% taught`,
  );

  // --- Clear what this seed owns --------------------------------------------
  /**
   * Only this year's rows are removed, and in dependency order, so the seed can
   * be re-run without either duplicating a school or taking the archive down
   * with it. The order matters: `attendance.student_id` is ON DELETE RESTRICT,
   * so children go before parents throughout.
   */
  for (const sql of [
    `DELETE FROM submissions WHERE assignment_id IN (SELECT id FROM assignments WHERE academic_year_id = $1)`,
    `DELETE FROM assignments WHERE academic_year_id = $1`,
    `DELETE FROM exam_results WHERE exam_id IN (SELECT id FROM exams WHERE academic_year_id = $1)`,
    `DELETE FROM exams WHERE academic_year_id = $1`,
    `DELETE FROM report_card_subjects WHERE report_card_id IN (SELECT id FROM report_cards WHERE academic_year_id = $1)`,
    `DELETE FROM report_cards WHERE academic_year_id = $1`,
    `DELETE FROM grade_history WHERE grade_id IN (SELECT id FROM grades WHERE academic_year_id = $1)`,
    `DELETE FROM grades WHERE academic_year_id = $1`,
    `DELETE FROM assessment_results WHERE assessment_id IN (SELECT id FROM assessments WHERE academic_year_id = $1)`,
    `DELETE FROM assessments WHERE academic_year_id = $1`,
    `DELETE FROM attendance WHERE academic_year_id = $1`,
    `DELETE FROM student_behaviors WHERE academic_year_id = $1`,
    `DELETE FROM student_comments WHERE academic_year_id = $1`,
    `DELETE FROM schedules WHERE academic_year_id = $1`,
    `DELETE FROM enrollments WHERE academic_year_id = $1`,
    `DELETE FROM class_subjects WHERE class_id IN (SELECT id FROM classes WHERE academic_year_id = $1)`,
    `DELETE FROM teacher_classes WHERE class_id IN (SELECT id FROM classes WHERE academic_year_id = $1)`,
    `DELETE FROM classes WHERE academic_year_id = $1`,
  ]) {
    await client.query(sql, [yearId]);
  }

  /**
   * Remove the intake a previous run invented.
   *
   * Deleting the year's enrolments above orphans the generated Grade 7 pupils —
   * they belong to no year at all — and leaving them would add a fresh intake on
   * top of the last one every time the seed ran. Only pupils carrying this
   * seed's marker and holding no enrolment anywhere are removed, so a real child
   * can never be caught by it.
   */
  const orphaned = await client.query(
    `DELETE FROM students s
      WHERE s.notes = $1
        AND NOT EXISTS (SELECT 1 FROM enrollments e WHERE e.student_id = s.id)`,
    [GENERATED_MARKER],
  );

  if (orphaned.rowCount) {
    logger.info(`Removed ${orphaned.rowCount} generated pupil(s) left by an earlier run`);
  }

  // --- Classes ---------------------------------------------------------------
  /**
   * Three sections per grade. The sizes are set by who is moving up rather than
   * chosen: last year's 127 Grade 7 pupils have to fit into Grade 8 and its 143
   * Grade 8 pupils into Grade 9, which two sections of fifty could not hold.
   */
  const gradeLevels = (
    await client.query<{ id: number; code: string; level_order: number }>(
      'SELECT id, code, level_order FROM grade_levels WHERE deleted_at IS NULL ORDER BY level_order',
    )
  ).rows;

  const teachers = (
    await client.query<{ id: number; subject_code: string }>(
      `SELECT t.id, s.code AS subject_code
         FROM teachers t
         JOIN teacher_subjects ts ON ts.teacher_id = t.id
         JOIN subjects s ON s.id = ts.subject_id
        WHERE t.deleted_at IS NULL
        ORDER BY t.id`,
    )
  ).rows;

  const classes: ClassRow[] = [];
  let homeroomCursor = 0;

  for (const grade of gradeLevels) {
    for (const section of ['A', 'B', 'C']) {
      const code = `${grade.level_order}${section}`;

      /**
       * A room per class, created when the school has not got one. Grade 9 only
       * ever ran two sections before, so Room 9C does not exist yet.
       */
      const room = (
        await client.query<{ id: number }>(
          `INSERT INTO rooms (code, name, capacity, is_active)
           VALUES ($1, $2, 45, TRUE)
           ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name
           RETURNING id`,
          [code, `Room ${code}`],
        )
      ).rows[0];

      const homeroom = teachers[homeroomCursor % teachers.length];
      homeroomCursor += 1;

      const created = (
        await client.query<{ id: number }>(
          `INSERT INTO classes (academic_year_id, grade_level_id, homeroom_teacher_id, room_id,
                                code, name, capacity, is_active)
           VALUES ($1, $2, $3, $4, $5, $6, 50, TRUE)
           RETURNING id`,
          [yearId, grade.id, homeroom.id, room.id, code, `Grade ${code}`],
        )
      ).rows[0];

      await client.query(
        `INSERT INTO teacher_classes (teacher_id, class_id, is_homeroom)
         VALUES ($1, $2, TRUE)
         ON CONFLICT (teacher_id, class_id) DO UPDATE SET is_homeroom = TRUE`,
        [homeroom.id, created.id],
      );

      classes.push({ id: created.id, code, gradeLevelId: grade.id, gradeCode: grade.code });
    }
  }

  counts.classes = classes.length;

  // --- Who moves up, and who is new -----------------------------------------
  /**
   * Continuity is the whole point of `enrollments`: the same child appears in
   * one year in Grade 7 and the next in Grade 8, and their history is the chain
   * of enrolments rather than a column on the pupil. So the roster of this year
   * is built from last year's, not invented.
   *
   * Grade 9 is the exit grade, so its pupils have left and are not carried
   * forward; a fresh Grade 7 intake replaces them at the bottom of the school.
   */
  const previous = (
    await client.query<{ student_id: number; grade_order: number }>(
      `SELECT DISTINCT ON (e.student_id) e.student_id, g.level_order AS grade_order
         FROM enrollments e
         JOIN classes c ON c.id = e.class_id
         JOIN grade_levels g ON g.id = c.grade_level_id
         JOIN students s ON s.id = e.student_id
        WHERE e.academic_year_id <> $1
          AND s.deleted_at IS NULL
          AND s.status <> 'GRADUATED'
          AND g.is_exit_grade = FALSE
        ORDER BY e.student_id, e.enrolled_date DESC`,
      [yearId],
    )
  ).rows;

  const movingUp = new Map<number, number[]>();

  for (const row of previous) {
    const target = row.grade_order + 1;
    movingUp.set(target, [...(movingUp.get(target) ?? []), row.student_id]);
  }

  /** The new Grade 7 intake, sized so the year group matches the ones above it. */
  const INTAKE = 126;
  const intakeIds: number[] = [];
  const startYear = Number(calendar.start.slice(0, 4));

  /**
   * Codes continue this year's own run rather than the highest number anywhere.
   * Reading every code at once and taking the maximum produced
   * `STU-2026-202620250606`, because the digits of a whole code are not a
   * sequence number.
   */
  const nextCode = Number(
    (
      await client.query<{ next: string }>(
        `SELECT COALESCE(MAX(SUBSTRING(student_code FROM '\\d+$')::int), 0) + 1 AS next
           FROM students WHERE student_code ~ $1`,
        // Anchored to exactly four trailing digits, so a malformed code left
        // by an older run is not read as a sequence number and overflowed.
        [`^STU-${startYear}-[0-9]{4}$`],
      )
    ).rows[0].next,
  );

  for (let index = 0; index < INTAKE; index += 1) {
    const isBoy = random() < 0.49;
    const [firstKh, firstEn] = (isBoy ? GIVEN_MALE : GIVEN_FEMALE)[
      Math.floor(random() * (isBoy ? GIVEN_MALE : GIVEN_FEMALE).length)
    ];
    const [lastKh, lastEn] = FAMILY[Math.floor(random() * FAMILY.length)];

    // Grade 7 pupils are twelve or thirteen at the start of the year.
    const birthYear = startYear - 13;
    const birthday = addDays(
      `${birthYear}-01-01`,
      Math.floor(random() * 365),
    );

    const created = (
      await client.query<{ id: number }>(
        `INSERT INTO students (student_code, first_name_en, last_name_en, first_name_kh,
                               last_name_kh, gender, date_of_birth, province,
                               enrolled_date, status, notes)
         VALUES ($1, $2, $3, $4, $5, $6::gender, $7, $8, $9, 'ACTIVE', $10)
         RETURNING id`,
        [
          `STU-${startYear}-${pad(nextCode + index, 4)}`,
          firstEn, lastEn, firstKh, lastKh,
          isBoy ? 'MALE' : 'FEMALE',
          birthday,
          PROVINCES[Math.floor(random() * PROVINCES.length)],
          calendar.start,
          GENERATED_MARKER,
        ],
      )
    ).rows[0];

    intakeIds.push(created.id);
  }

  movingUp.set(7, [...(movingUp.get(7) ?? []), ...intakeIds]);
  counts.newStudents = intakeIds.length;

  /**
   * Pupils are spread across the sections of their grade in round-robin order,
   * which keeps the sections within a few pupils of each other rather than
   * filling 8A to the brim and leaving 8C half empty.
   */
  const enrollmentRows: unknown[][] = [];
  const pupils: Pupil[] = [];

  for (const grade of gradeLevels) {
    const sections = classes.filter((entry) => entry.gradeLevelId === grade.id);
    const cohort = movingUp.get(grade.level_order) ?? [];
    const rolls = new Map<number, number>();

    cohort.forEach((studentId, index) => {
      const section = sections[index % sections.length];
      const roll = (rolls.get(section.id) ?? 0) + 1;
      rolls.set(section.id, roll);

      enrollmentRows.push([
        studentId, yearId, section.id, pad(roll, 2), calendar.start, 'ACTIVE',
      ]);
    });
  }

  await insertMany(
    client,
    'enrollments',
    ['student_id', 'academic_year_id', 'class_id', 'roll_number', 'enrolled_date', 'status'],
    enrollmentRows,
    { 5: 'enrollment_status' },
  );

  for (const row of (
    await client.query<{ id: number; student_id: number; class_id: number }>(
      'SELECT id, student_id, class_id FROM enrollments WHERE academic_year_id = $1',
      [yearId],
    )
  ).rows) {
    pupils.push({ studentId: row.student_id, enrollmentId: row.id, classId: row.class_id });
  }

  const rosterOf = new Map<number, Pupil[]>();

  for (const pupil of pupils) {
    rosterOf.set(pupil.classId, [...(rosterOf.get(pupil.classId) ?? []), pupil]);
  }

  const profiles = new Map<number, Profile>(
    pupils.map((pupil) => [pupil.studentId, profileFor(pupil.studentId)]),
  );

  counts.enrollments = pupils.length;
  logger.info(
    `Roster: ${pupils.length} pupils across ${classes.length} classes ` +
      `(${intakeIds.length} new in Grade 7, ${pupils.length - intakeIds.length} moved up)`,
  );

  // --- Guardians for the new intake -----------------------------------------
  /**
   * The pupils who moved up already have guardians, because `student_parents`
   * links a family to a child rather than to a year. The new Grade 7 intake has
   * nobody, and a child registered at a Cambodian secondary school without a
   * guardian on record is not a realistic row — it would also leave the parent
   * portal empty for a sixth of the school.
   *
   * A guardian takes the child's family name, which is what makes the pairing
   * read as a household rather than two unrelated people. A quarter of them ask
   * for a portal login; the rest are recorded on paper only, as at the school.
   */
  /**
   * Guardians left behind when the previous intake was removed.
   *
   * `parents` has no notes column to mark, but this seed owns the whole
   * `PAR-<year>-` code range, so a guardian with one of those codes and no child
   * left to answer for can only be one of its own.
   */
  await client.query(
    `DELETE FROM parents p
      WHERE p.parent_code LIKE $1
        AND NOT EXISTS (SELECT 1 FROM student_parents sp WHERE sp.parent_id = p.id)`,
    [`PAR-${startYear}-%`],
  );

  const guardianPassword = await hashPassword(GUARDIAN_PASSWORD);
  let guardianSeq = Number(
    (
      await client.query<{ next: string }>(
        `SELECT COALESCE(MAX(SUBSTRING(parent_code FROM '\d+$')::int), 0) AS next
           FROM parents WHERE parent_code LIKE $1`,
        [`PAR-${startYear}-%`],
      )
    ).rows[0].next,
  );
  let guardianLogins = 0;
  let guardianCount = 0;

  for (const studentId of intakeIds) {
    const child = (
      await client.query<{ last_kh: string; last_en: string }>(
        'SELECT last_name_kh AS last_kh, last_name_en AS last_en FROM students WHERE id = $1',
        [studentId],
      )
    ).rows[0];

    const isFather = random() < 0.55;
    const [firstKh, firstEn] = (isFather ? GIVEN_MALE : GIVEN_FEMALE)[
      Math.floor(random() * (isFather ? GIVEN_MALE : GIVEN_FEMALE).length)
    ];

    guardianSeq += 1;
    let userId: number | null = null;

    if (random() < 0.25) {
      const username = `parent${startYear}${pad(guardianSeq, 4)}`;
      const inserted = await client.query<{ id: number }>(
        `INSERT INTO users (username, email, password_hash, status, email_verified_at)
         VALUES ($1, $2, $3, 'ACTIVE', NOW())
         ON CONFLICT DO NOTHING
         RETURNING id`,
        [username, `${username}@school.local`, guardianPassword],
      );

      if (inserted.rows[0]) {
        userId = inserted.rows[0].id;
        guardianLogins += 1;
        await client.query(
          `INSERT INTO user_roles (user_id, role_id)
           SELECT $1, id FROM roles WHERE code = 'PARENT' ON CONFLICT DO NOTHING`,
          [userId],
        );
      }
    }

    const guardian = await client.query<{ id: number }>(
      `INSERT INTO parents (user_id, parent_code, first_name_en, last_name_en,
                            first_name_kh, last_name_kh, gender, phone_number,
                            occupation, province, is_active)
       VALUES ($1, $2, $3, $4, $5, $6, $7::gender, $8, $9, $10, TRUE)
       RETURNING id`,
      [
        userId,
        `PAR-${startYear}-${pad(guardianSeq, 4)}`,
        firstEn, child.last_en, firstKh, child.last_kh,
        isFather ? 'MALE' : 'FEMALE',
        `0${6 + Math.floor(random() * 4)}${pad(Math.floor(random() * 10000000), 7)}`,
        OCCUPATIONS[Math.floor(random() * OCCUPATIONS.length)],
        PROVINCES[Math.floor(random() * PROVINCES.length)],
      ],
    );

    await client.query(
      `INSERT INTO student_parents (student_id, parent_id, relationship, is_primary_contact, is_emergency_contact)
       VALUES ($1, $2, $3::guardian_relationship, TRUE, TRUE)
       ON CONFLICT DO NOTHING`,
      [studentId, guardian.rows[0].id, isFather ? 'FATHER' : 'MOTHER'],
    );

    guardianCount += 1;
  }

  counts.guardians = guardianCount;
  logger.info(
    `Guardians: ${guardianCount} registered for the new intake, ${guardianLogins} with a portal login`,
  );

  // --- Timetable -------------------------------------------------------------
  /**
   * Reuses the timetable seed rather than repeating it: it already assigns each
   * class its subject teachers and lays out a conflict-free week, and it works
   * on whichever year is active — which, by this point, is this one.
   */
  await seedTimetable(client);

  const classSubjects = (
    await client.query<{
      class_id: number; subject_id: number; subject_code: string;
      subject_name: string; teacher_id: number | null;
    }>(
      `SELECT cs.class_id, cs.subject_id, s.code AS subject_code,
              s.name_en AS subject_name, cs.teacher_id
         FROM class_subjects cs
         JOIN classes c ON c.id = cs.class_id
         JOIN subjects s ON s.id = cs.subject_id
        WHERE c.academic_year_id = $1 AND cs.teacher_id IS NOT NULL
        ORDER BY cs.class_id, s.code`,
      [yearId],
    )
  ).rows;

  counts.classSubjects = classSubjects.length;
  counts.schedules = (
    await client.query<{ n: string }>(
      'SELECT COUNT(*) AS n FROM schedules WHERE academic_year_id = $1',
      [yearId],
    )
  ).rows[0].n as unknown as number;

  // --- The daily register ----------------------------------------------------
  /**
   * Semester 1 is registered to its last day. Semester 2 stops at today, which
   * is the single most important date rule in this seed: a register with
   * tomorrow's absences in it is not a half-taught term, it is a broken one.
   *
   * Each pupil is marked against their own attendance rate rather than a rate
   * shared by the school, so the year produces the spread a real register has —
   * a majority near the top, a middle band, and a handful who are genuinely
   * missing lessons.
   */
  const reasons = (
    await client.query<{ id: number; code: string }>('SELECT id, code FROM attendance_reasons')
  ).rows;
  const reasonFor = (code: string): number | null =>
    reasons.find((entry) => entry.code === code)?.id ?? null;

  const attendanceRows: unknown[][] = [];
  const termDays = new Map<number, IsoDate[]>();

  for (const term of terms) {
    const days = schoolDays(term.start, term.end, today);
    termDays.set(term.order, days);

    for (const day of days) {
      for (const pupil of pupils) {
        const profile = profiles.get(pupil.studentId) as Profile;
        const roll = random();

        /**
         * Absence is split rather than lumped: most of what a pupil misses is
         * lateness or an excused day, and only the remainder is an unexplained
         * absence. Treating every miss as an absence makes a 90% attender look
         * like a truant.
         */
        const missing = 1 - profile.attendance;
        const status =
          roll >= missing ? 'PRESENT'
          : roll < missing * 0.42 ? 'LATE'
          : roll < missing * 0.70 ? 'ABSENT'
          : roll < missing * 0.90 ? 'EXCUSED'
          : 'LEAVE';

        attendanceRows.push([
          pupil.studentId, pupil.classId, pupil.enrollmentId, yearId, day, status,
          status === 'LATE' ? 5 + Math.floor(random() * 26) : null,
          status === 'EXCUSED' ? reasonFor('SICK')
          : status === 'LEAVE' ? reasonFor('APPROVED_LEAVE')
          : status === 'ABSENT' ? reasonFor('UNEXCUSED')
          : status === 'LATE' ? reasonFor('TRAFFIC')
          : null,
        ]);
      }
    }
  }

  counts.attendance = await insertMany(
    client,
    'attendance',
    ['student_id', 'class_id', 'enrollment_id', 'academic_year_id', 'attendance_date',
      'status', 'minutes_late', 'reason_id'],
    attendanceRows,
    { 5: 'attendance_status' },
  );

  logger.info(
    `Register: ${attendanceRows.length} entries — ` +
      `${(termDays.get(1) ?? []).length} days in Semester 1, ` +
      `${(termDays.get(2) ?? []).length} so far in Semester 2`,
  );

  // --- Assessments -----------------------------------------------------------
  /**
   * Every piece of work in both semesters is created, because a teacher plans a
   * term in advance and the timetable of assessments is part of that plan. What
   * separates the finished semester from the running one is not which
   * assessments exist but which have been sat: a piece dated after today is a
   * scheduled assessment with no marks against it, and the final examination of
   * Semester 2 is exactly that.
   *
   * Two subjects in each class are also left unmarked in Semester 2 even though
   * their date has passed — their teacher has not entered the marks yet. That is
   * the ordinary state of a school mid-term, and it is what makes "no mark yet"
   * distinguishable from "no assessment".
   */
  const behindOn = new Set<string>();

  for (const entry of classes) {
    const subjectsHere = classSubjects.filter((pair) => pair.class_id === entry.id);
    const shuffled = [...subjectsHere].sort(() => random() - 0.5);

    for (const pair of shuffled.slice(0, 2)) {
      behindOn.add(`${pair.class_id}:${pair.subject_id}`);
    }
  }

  const assessmentRows: unknown[][] = [];

  for (const term of terms) {
    const termId = termIds.get(term.order) as number;

    for (const pair of classSubjects) {
      for (const piece of PIECES) {
        const on = dateWithin(term.start, term.end, piece.at);

        assessmentRows.push([
          yearId, termId, pair.class_id, pair.subject_id, pair.teacher_id,
          `${pair.subject_name} — ${piece.label}`,
          piece.type, piece.max, on,
          // An assessment the pupils have not sat is not shown to them yet.
          on <= today,
        ]);
      }
    }
  }

  await insertMany(
    client,
    'assessments',
    ['academic_year_id', 'term_id', 'class_id', 'subject_id', 'teacher_id',
      'title', 'type', 'max_score', 'assessment_date', 'is_published'],
    assessmentRows,
    { 6: 'assessment_type' },
  );

  const assessments = (
    await client.query<{
      id: number; class_id: number; subject_id: number; term_id: number;
      type: string; max_score: string; assessment_date: string;
    }>(
      `SELECT id, class_id, subject_id, term_id, type::text, max_score, assessment_date::text
         FROM assessments WHERE academic_year_id = $1 ORDER BY id`,
      [yearId],
    )
  ).rows;

  counts.assessments = assessments.length;

  /**
   * A pupil's expected percentage in one subject.
   *
   * Their ability sets the centre and a per-subject offset moves it, so the same
   * child is consistently stronger in the same subjects. The offsets are drawn
   * from the pupil's own id and then have their mean removed, which keeps the
   * variation without dragging the pupil's overall average away from the ability
   * they were given.
   */
  const subjectIds = [...new Set(classSubjects.map((pair) => pair.subject_id))].sort(
    (a, b) => a - b,
  );

  const offsetsFor = new Map<number, Map<number, number>>();

  for (const pupil of pupils) {
    const draw = makeRandom(pupil.studentId * 40503);
    const raw = subjectIds.map(() => draw() * 18 - 9);
    const mean = raw.reduce((sum, value) => sum + value, 0) / raw.length;

    offsetsFor.set(
      pupil.studentId,
      new Map(subjectIds.map((id, index) => [id, raw[index] - mean])),
    );
  }

  const targetFor = (studentId: number, subjectId: number): number => {
    const profile = profiles.get(studentId) as Profile;
    const offset = offsetsFor.get(studentId)?.get(subjectId) ?? 0;

    return Math.max(8, Math.min(99, profile.ability + offset));
  };

  const resultRows: unknown[][] = [];
  let unmarked = 0;

  for (const assessment of assessments) {
    // Not sat yet: the assessment stands, with nothing recorded against it.
    if (assessment.assessment_date > today) {
      continue;
    }

    // Sat, but this teacher has not entered Semester 2 marks yet.
    if (
      assessment.term_id === termIds.get(2) &&
      behindOn.has(`${assessment.class_id}:${assessment.subject_id}`)
    ) {
      continue;
    }

    const roster = rosterOf.get(assessment.class_id) ?? [];
    const max = Number(assessment.max_score);
    const running = assessment.term_id === termIds.get(2);

    for (const pupil of roster) {
      const profile = profiles.get(pupil.studentId) as Profile;

      /**
       * A pupil who was away for the paper is marked absent rather than given a
       * zero, because a zero would drag their grade down as though they had sat
       * it and failed.
       */
      if (random() > profile.attendance + 0.02) {
        resultRows.push([assessment.id, pupil.studentId, pupil.enrollmentId, null, true, null]);
        continue;
      }

      /**
       * In the running semester a few papers are sat but still on the marking
       * pile, so the row exists with no score. Nothing in the finished semester
       * is left in that state — that is what finished means.
       */
      if (running && random() < 0.06) {
        resultRows.push([assessment.id, pupil.studentId, pupil.enrollmentId, null, false, null]);
        unmarked += 1;
        continue;
      }

      const target = targetFor(pupil.studentId, assessment.subject_id);
      const percent = Math.max(0, Math.min(100, target + random() * 9 - 4.5));

      resultRows.push([
        assessment.id, pupil.studentId, pupil.enrollmentId,
        Number(((percent / 100) * max).toFixed(2)), false, new Date(),
      ]);
    }
  }

  counts.assessmentResults = await insertMany(
    client,
    'assessment_results',
    ['assessment_id', 'student_id', 'enrollment_id', 'score', 'is_absent', 'graded_at'],
    resultRows,
  );

  logger.info(
    `Marking: ${assessments.length} assessments, ${resultRows.length} results, ` +
      `${unmarked} sat but not yet marked, ` +
      `${assessments.filter((a) => a.assessment_date > today).length} scheduled and not yet sat`,
  );

  // --- Examinations ----------------------------------------------------------
  /**
   * The midterm and final are sittings as well as marks, so each one also gets
   * an `exams` row. The score copied onto it is the score already recorded
   * against the matching assessment, so the exam page and the grade page can
   * never disagree.
   *
   * The final examination of Semester 2 is created and has no results at all:
   * the school has scheduled it, the pupils have not sat it, and that is what
   * the request asks the data to show.
   */
  const scoreByAssessment = new Map<number, Map<number, number | null>>();

  for (const row of (
    await client.query<{ assessment_id: number; student_id: number; score: string | null }>(
      `SELECT ar.assessment_id, ar.student_id, ar.score
         FROM assessment_results ar
         JOIN assessments a ON a.id = ar.assessment_id
        WHERE a.academic_year_id = $1`,
      [yearId],
    )
  ).rows) {
    const byStudent = scoreByAssessment.get(row.assessment_id) ?? new Map();
    byStudent.set(row.student_id, row.score === null ? null : Number(row.score));
    scoreByAssessment.set(row.assessment_id, byStudent);
  }

  const sittings = assessments.filter(
    (entry) => entry.type === 'MIDTERM' || entry.type === 'FINAL',
  );

  const examRows: unknown[][] = [];

  for (const sitting of sittings) {
    const pair = classSubjects.find(
      (entry) => entry.class_id === sitting.class_id && entry.subject_id === sitting.subject_id,
    );

    examRows.push([
      yearId, sitting.term_id, sitting.class_id, sitting.subject_id,
      `${pair?.subject_name ?? 'Subject'} — ${sitting.type === 'MIDTERM' ? 'Midterm' : 'Final'} examination`,
      sitting.type, sitting.assessment_date, sitting.max_score, 90,
    ]);
  }

  await insertMany(
    client,
    'exams',
    ['academic_year_id', 'term_id', 'class_id', 'subject_id', 'title', 'type',
      'exam_date', 'max_score', 'duration_minutes'],
    examRows,
    { 5: 'exam_type' },
  );

  const exams = (
    await client.query<{
      id: number; class_id: number; subject_id: number; term_id: number;
      type: string; exam_date: string;
    }>(
      `SELECT id, class_id, subject_id, term_id, type::text, exam_date::text
         FROM exams WHERE academic_year_id = $1`,
      [yearId],
    )
  ).rows;

  const examResultRows: unknown[][] = [];

  for (const exam of exams) {
    if (exam.exam_date > today) {
      continue;
    }

    const source = sittings.find(
      (entry) =>
        entry.class_id === exam.class_id &&
        entry.subject_id === exam.subject_id &&
        entry.term_id === exam.term_id &&
        entry.type === exam.type,
    );

    const marks = source ? scoreByAssessment.get(source.id) : undefined;

    if (!marks) {
      continue;
    }

    for (const [studentId, score] of marks) {
      examResultRows.push([exam.id, studentId, score, score === null]);
    }
  }

  counts.exams = exams.length;
  counts.examResults = await insertMany(
    client,
    'exam_results',
    ['exam_id', 'student_id', 'score', 'is_absent'],
    examResultRows,
  );

  logger.info(
    `Examinations: ${exams.length} sittings, ${examResultRows.length} results, ` +
      `${exams.filter((e) => e.exam_date > today).length} scheduled with no marks`,
  );

  // --- Subject grades --------------------------------------------------------
  /**
   * A grade is the weighted total of the marks behind it, not a number invented
   * beside them, so it is computed from `assessment_results` using the weights
   * in `grading_scheme_components`. Recalculating in the application produces
   * the same figure.
   *
   * The two semesters differ in what a grade means. Semester 1 is weighted over
   * every piece of work and marked `is_final`. Semester 2 is weighted over the
   * pieces sat so far and left provisional, and where a teacher has not entered
   * marks at all there is no grade row — the subject is simply not yet assessed,
   * which is different from having been assessed at zero.
   */
  const scheme = (
    await client.query<{ id: number }>(
      `SELECT id FROM grading_schemes WHERE code = 'STANDARD' LIMIT 1`,
    )
  ).rows[0]?.id ?? null;

  const scales = (
    await client.query<{
      letter_grade: string; min_score: string; max_score: string;
      gpa_point: string | null; performance: string;
    }>('SELECT letter_grade, min_score, max_score, gpa_point, performance FROM grade_scales')
  ).rows;

  const band = (percent: number) =>
    scales.find(
      (scale) => percent >= Number(scale.min_score) && percent <= Number(scale.max_score),
    );

  interface Tally { earned: number; possible: number }

  const tallies = new Map<string, Map<string, Tally>>();
  const assessmentById = new Map(assessments.map((entry) => [entry.id, entry]));

  for (const [assessmentId, marks] of scoreByAssessment) {
    const assessment = assessmentById.get(assessmentId);

    if (!assessment) {
      continue;
    }

    for (const [studentId, score] of marks) {
      // An absent or unmarked paper contributes nothing to either side of the
      // ratio, so it lowers no grade while it waits.
      if (score === null) {
        continue;
      }

      const key = `${studentId}:${assessment.class_id}:${assessment.subject_id}:${assessment.term_id}`;
      const byType = tallies.get(key) ?? new Map<string, Tally>();
      const tally = byType.get(assessment.type) ?? { earned: 0, possible: 0 };

      tally.earned += score;
      tally.possible += Number(assessment.max_score);
      byType.set(assessment.type, tally);
      tallies.set(key, byType);
    }
  }

  interface Computed {
    studentId: number; classId: number; subjectId: number; termId: number;
    percentage: number; enrollmentId: number;
  }

  const enrollmentOf = new Map(pupils.map((pupil) => [pupil.studentId, pupil.enrollmentId]));
  const computed: Computed[] = [];

  for (const [key, byType] of tallies) {
    const [studentId, classId, subjectId, termId] = key.split(':').map(Number);
    let weighted = 0;
    let used = 0;

    for (const [type, tally] of byType) {
      if (tally.possible <= 0) {
        continue;
      }

      const weight = WEIGHTS[type] ?? 0;
      weighted += (tally.earned / tally.possible) * 100 * weight;
      used += weight;
    }

    if (used <= 0) {
      continue;
    }

    computed.push({
      studentId, classId, subjectId, termId,
      percentage: Number((weighted / used).toFixed(2)),
      enrollmentId: enrollmentOf.get(studentId) as number,
    });
  }

  // Rank within the class, per subject and term.
  const rankGroups = new Map<string, Computed[]>();

  for (const row of computed) {
    const key = `${row.classId}:${row.subjectId}:${row.termId}`;
    rankGroups.set(key, [...(rankGroups.get(key) ?? []), row]);
  }

  const rankOf = new Map<string, number>();

  for (const group of rankGroups.values()) {
    [...group]
      .sort((a, b) => b.percentage - a.percentage)
      .forEach((row, index) => {
        rankOf.set(`${row.studentId}:${row.subjectId}:${row.termId}`, index + 1);
      });
  }

  const firstTermId = termIds.get(1) as number;

  const gradeRows = computed.map((row) => {
    const scale = band(row.percentage);

    return [
      row.studentId, row.enrollmentId, yearId, row.termId, row.classId, row.subjectId, scheme,
      row.percentage, 100, row.percentage,
      scale?.letter_grade ?? null, scale?.performance ?? null,
      scale?.gpa_point == null ? null : Number(scale.gpa_point),
      rankOf.get(`${row.studentId}:${row.subjectId}:${row.termId}`) ?? null,
      // Only the finished semester's grades are final; the running one's are
      // provisional and will move as the rest of the term is marked.
      row.termId === firstTermId,
    ];
  });

  counts.grades = await insertMany(
    client,
    'grades',
    ['student_id', 'enrollment_id', 'academic_year_id', 'term_id', 'class_id', 'subject_id',
      'grading_scheme_id', 'score', 'max_score', 'percentage', 'letter_grade', 'performance',
      'gpa_point', 'rank_in_class', 'is_final'],
    gradeRows,
    { 11: 'performance_level' },
  );

  const finalGrades = gradeRows.filter((row) => row[3] === firstTermId).length;

  logger.info(
    `Grades: ${finalGrades} final for Semester 1, ` +
      `${gradeRows.length - finalGrades} provisional for Semester 2`,
  );

  // --- Report cards, for the finished semester only --------------------------
  /**
   * A report card is the settled result of a semester, so only Semester 1 has
   * them. Issuing one for a term that is half taught would state an average and
   * a rank the school has not arrived at, and there is no honest status for
   * that — which is why the running semester has no cards at all rather than
   * empty ones.
   */
  const bySubject = new Map<string, Computed[]>();

  for (const row of computed.filter((entry) => entry.termId === firstTermId)) {
    bySubject.set(
      `${row.studentId}`,
      [...(bySubject.get(`${row.studentId}`) ?? []), row],
    );
  }

  const overall: { studentId: number; classId: number; percentage: number }[] = [];

  for (const [studentId, rows] of bySubject) {
    const mean = rows.reduce((sum, row) => sum + row.percentage, 0) / rows.length;
    overall.push({
      studentId: Number(studentId),
      classId: rows[0].classId,
      percentage: Number(mean.toFixed(2)),
    });
  }

  const classRank = new Map<number, number>();
  const classSize = new Map<number, number>();

  for (const entry of classes) {
    const inClass = overall
      .filter((row) => row.classId === entry.id)
      .sort((a, b) => b.percentage - a.percentage);

    inClass.forEach((row, index) => classRank.set(row.studentId, index + 1));
    inClass.forEach((row) => classSize.set(row.studentId, inClass.length));
  }

  const REMARKS: Record<string, string[]> = {
    EXCELLENT: [
      'Consistently strong across every subject. A pleasure to teach.',
      'Excellent work all semester, and a good example to the class.',
    ],
    GOOD: [
      'A solid semester. With steady revision the top band is within reach.',
      'Good progress, particularly in the second half of the term.',
    ],
    FAIR: [
      'Reaching the standard, but the marks slip when homework is missed.',
      'Capable of more. Regular attendance would show in these results.',
    ],
    NEEDS_IMPROVEMENT: [
      'Falling behind and needs support at home as well as in class.',
      'Attendance and unfinished homework are holding these results back.',
    ],
  };

  const cardRows: unknown[][] = [];

  for (const row of overall) {
    const scale = band(row.percentage);
    const remarks = REMARKS[scale?.performance ?? 'FAIR'] ?? REMARKS.FAIR;

    cardRows.push([
      row.studentId, enrollmentOf.get(row.studentId) ?? null, yearId, firstTermId, row.classId,
      row.percentage, row.percentage,
      scale?.gpa_point == null ? null : Number(scale.gpa_point),
      scale?.letter_grade ?? null, scale?.performance ?? null,
      classRank.get(row.studentId) ?? null, classSize.get(row.studentId) ?? null,
      remarks[Math.floor(random() * remarks.length)],
      'PUBLISHED', new Date(), new Date(),
    ]);
  }

  await insertMany(
    client,
    'report_cards',
    ['student_id', 'enrollment_id', 'academic_year_id', 'term_id', 'class_id',
      'total_score', 'average_score', 'gpa', 'letter_grade', 'performance',
      'rank_in_class', 'class_size', 'homeroom_comment', 'status',
      'generated_at', 'published_at'],
    cardRows,
    { 9: 'performance_level', 13: 'report_card_status' },
  );

  const cards = (
    await client.query<{ id: number; student_id: number }>(
      'SELECT id, student_id FROM report_cards WHERE academic_year_id = $1 AND term_id = $2',
      [yearId, firstTermId],
    )
  ).rows;

  const cardIdOf = new Map(cards.map((card) => [card.student_id, card.id]));
  const subjectOrder = new Map(subjectIds.map((id, index) => [id, index + 1]));
  const cardSubjectRows: unknown[][] = [];

  for (const row of computed.filter((entry) => entry.termId === firstTermId)) {
    const cardId = cardIdOf.get(row.studentId);

    if (!cardId) {
      continue;
    }

    const scale = band(row.percentage);

    cardSubjectRows.push([
      cardId, row.subjectId, row.percentage, 100, row.percentage,
      scale?.letter_grade ?? null, scale?.performance ?? null,
      rankOf.get(`${row.studentId}:${row.subjectId}:${row.termId}`) ?? null,
      subjectOrder.get(row.subjectId) ?? 0,
    ]);
  }

  counts.reportCards = cards.length;
  counts.reportCardSubjects = await insertMany(
    client,
    'report_card_subjects',
    ['report_card_id', 'subject_id', 'score', 'max_score', 'percentage',
      'letter_grade', 'performance', 'rank_in_class', 'display_order'],
    cardSubjectRows,
    { 6: 'performance_level' },
  );

  /**
   * Copy the register onto each card.
   *
   * The attendance columns are what a parent actually looks at, and leaving them
   * at zero puts a dash on the printed card where a figure belongs.
   */
  await client.query(
    `UPDATE report_cards rc
        SET days_present = t.present,
            days_absent = t.absent,
            days_late = t.late,
            days_excused = t.excused,
            attendance_percent = CASE WHEN t.total > 0
              THEN ROUND(100.0 * (t.present + t.late) / t.total, 2) ELSE NULL END
       FROM (
         SELECT rc2.id,
                COUNT(*) FILTER (WHERE a.status = 'PRESENT')::int AS present,
                COUNT(*) FILTER (WHERE a.status = 'ABSENT')::int AS absent,
                COUNT(*) FILTER (WHERE a.status = 'LATE')::int AS late,
                COUNT(*) FILTER (WHERE a.status IN ('EXCUSED', 'LEAVE'))::int AS excused,
                COUNT(*)::int AS total
           FROM report_cards rc2
           JOIN academic_terms term ON term.id = rc2.term_id
           JOIN attendance a
             ON a.student_id = rc2.student_id
            AND a.academic_year_id = rc2.academic_year_id
            AND a.attendance_date BETWEEN term.start_date AND term.end_date
          WHERE rc2.academic_year_id = $1
          GROUP BY rc2.id
       ) t
      WHERE rc.id = t.id`,
    [yearId],
  );

  logger.info(`Report cards: ${cards.length} published for Semester 1, none for Semester 2`);

  // --- Homework --------------------------------------------------------------
  /**
   * Homework is where the difference between the two semesters is most visible,
   * because an assignment passes through states that a finished term has all
   * left behind.
   *
   * Four kinds are set per subject per term, positioned so that in the running
   * semester one of each state exists at once: work marked and closed, work
   * handed in and waiting on the teacher, work whose deadline has not arrived,
   * and work the teacher has drafted but not yet published. In the finished
   * semester every one of them has come to rest as CLOSED.
   */
  /**
   * How long a teacher takes to mark a set before closing it.
   *
   * This gap is the whole reason the running semester shows work that is
   * overdue but not yet graded. With no lag every deadline that passes would
   * close instantly, and the LATE and SUBMITTED states — a pupil has handed in,
   * the teacher has not got to it — could never occur.
   */
  const MARKING_LAG_DAYS = 21;

  const TASKS: { label: string; at: number; days: number }[] = [
    { label: 'Exercise book', at: 0.18, days: 7 },
    { label: 'Practice worksheet', at: 0.34, days: 6 },
    { label: 'Chapter questions', at: 0.46, days: 7 },
    { label: 'Term project', at: 0.62, days: 10 },
  ];

  const assignmentRows: unknown[][] = [];

  for (const term of terms) {
    const termId = termIds.get(term.order) as number;

    for (const pair of classSubjects) {
      for (const task of TASKS) {
        const assigned = dateWithin(term.start, term.end, task.at);
        const due = addDays(assigned, task.days);

        /**
         * The state follows the calendar rather than being picked: work not yet
         * set is a draft, work whose deadline has passed and has been marked is
         * closed, and everything between is published and open.
         */
        const status =
          assigned > today ? 'DRAFT'
          : due < addDays(today, -MARKING_LAG_DAYS) ? 'CLOSED'
          : 'PUBLISHED';

        assignmentRows.push([
          yearId, termId, pair.class_id, pair.subject_id, pair.teacher_id,
          `${pair.subject_name} — ${task.label}`,
          `${task.label} covering the current unit of ${pair.subject_name}.`,
          'Answer in your exercise book. A photograph or a PDF may be uploaded instead.',
          assigned, due, 20, status,
          status === 'DRAFT' ? null : new Date(),
        ]);
      }
    }
  }

  await insertMany(
    client,
    'assignments',
    ['academic_year_id', 'term_id', 'class_id', 'subject_id', 'teacher_id',
      'title', 'description', 'instructions', 'assigned_date', 'due_date',
      'max_score', 'status', 'published_at'],
    assignmentRows,
    { 11: 'assignment_status' },
  );

  const assignments = (
    await client.query<{
      id: number; class_id: number; subject_id: number; term_id: number;
      due_date: string; assigned_date: string; max_score: string; status: string;
    }>(
      `SELECT id, class_id, subject_id, term_id, due_date::text, assigned_date::text,
              max_score, status::text
         FROM assignments WHERE academic_year_id = $1 ORDER BY id`,
      [yearId],
    )
  ).rows;

  const submissionRows: unknown[][] = [];
  const tally: Record<string, number> = {
    PENDING: 0, SUBMITTED: 0, LATE: 0, GRADED: 0, MISSING: 0,
  };

  for (const assignment of assignments) {
    /**
     * A draft has been set by nobody's reckoning but the teacher's, so it has no
     * submissions. Creating rows against it would show pupils work they cannot
     * see.
     */
    if (assignment.status === 'DRAFT') {
      continue;
    }

    const roster = rosterOf.get(assignment.class_id) ?? [];
    const max = Number(assignment.max_score);
    const overdue = assignment.due_date < today;
    const marked = assignment.status === 'CLOSED';

    for (const pupil of roster) {
      const profile = profiles.get(pupil.studentId) as Profile;
      const roll = random();

      /**
       * Still open, deadline ahead. Most pupils have not started; the diligent
       * ones have already handed in.
       */
      if (!overdue) {
        if (roll < profile.diligence * 0.42) {
          submissionRows.push([
            assignment.id, pupil.studentId, 'SUBMITTED',
            'Uploaded from the student portal.', new Date(), null, null,
          ]);
          tally.SUBMITTED += 1;
        } else {
          submissionRows.push([assignment.id, pupil.studentId, 'PENDING', null, null, null, null]);
          tally.PENDING += 1;
        }

        continue;
      }

      // Deadline passed and nothing was handed in. The chance is scaled well
      // down from raw diligence: a school where a third of homework never
      // arrives is not a school, and the point of the tail is that a few pupils
      // miss a lot while most miss the occasional piece.
      if (roll < (1 - profile.diligence) * 0.28) {
        submissionRows.push([assignment.id, pupil.studentId, 'MISSING', null, null, null, null]);
        tally.MISSING += 1;
        continue;
      }

      const late = roll > 1 - (1 - profile.diligence) * 0.55;
      const target = targetFor(pupil.studentId, assignment.subject_id);
      const score = Math.max(
        0,
        Math.min(max, Number((((target + random() * 10 - 5) / 100) * max).toFixed(2))),
      );

      /**
       * Once the teacher has marked the set, everything in it is GRADED — late
       * or not, the lateness lives in the feedback. Before that, a handed-in
       * piece sits at SUBMITTED or LATE waiting for them, which is the state the
       * running semester needs to show.
       */
      if (marked) {
        submissionRows.push([
          assignment.id, pupil.studentId, 'GRADED',
          'Uploaded from the student portal.', new Date(), score,
          late ? 'Handed in after the deadline.' : 'Good work.',
        ]);
        tally.GRADED += 1;
      } else {
        submissionRows.push([
          assignment.id, pupil.studentId, late ? 'LATE' : 'SUBMITTED',
          'Uploaded from the student portal.', new Date(), null, null,
        ]);
        tally[late ? 'LATE' : 'SUBMITTED'] += 1;
      }
    }
  }

  counts.assignments = assignments.length;
  counts.submissions = await insertMany(
    client,
    'submissions',
    ['assignment_id', 'student_id', 'status', 'content', 'submitted_at', 'score', 'feedback'],
    submissionRows,
    { 2: 'submission_status' },
  );

  logger.info(
    `Homework: ${assignments.length} assignments ` +
      `(${assignments.filter((a) => a.status === 'DRAFT').length} draft, ` +
      `${assignments.filter((a) => a.status === 'PUBLISHED').length} open, ` +
      `${assignments.filter((a) => a.status === 'CLOSED').length} closed); ` +
      `submissions ${Object.entries(tally).map(([k, v]) => `${k} ${v}`).join(', ')}`,
  );

  return {
    yearName: YEAR_NAME,
    start: calendar.start,
    end: calendar.end,
    today,
    semester2Progress: taughtPercent,
    counts,
  };
};
